# Generated by Django 6.1.1 on 2026-10-03 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Como o jogador aparece no ranking. ate 24 caracteres.', max_length=24, verbose_name='Nome do jogador')),
                ('tempo', models.PositiveIntegerField(help_text='Duracao da partida em segundos.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo (segundos)')),
                ('inimigos_derrotados', models.PositiveIntegerField(help_text='Quantos inimigos foram derrubados na partida.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Inimigos derrotados')),
                ('pontuacao', models.PositiveIntegerField(help_text='Pontos da partida, ja calculado pelo jogo.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pontuacao final')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Partida no ranking',
                'verbose_name_plural': 'Ranking',
                'ordering': ['-pontuacao', 'tempo'],
            },
        ),
    ]
